/**
 * Embedded IANA timezone → city / country / coordinates table.
 * Zero network calls. Zero permission requests. Instantaneous lookup.
 * Covers all ~600 inhabited IANA zones; unmapped zones fall back to a
 * lat/lon derived from the UTC offset so Open-Meteo always gets valid coords.
 */

export interface TZLocation {
  city: string;
  country: string;
  lat: number;
  lon: number;
}

export const TIMEZONE_LOCATION: Record<string, TZLocation> = {
  // Africa
  'Africa/Abidjan':         { city: 'Abidjan',          country: 'Ivory Coast',               lat:  5.35, lon:  -4.00 },
  'Africa/Accra':           { city: 'Accra',             country: 'Ghana',                      lat:  5.56, lon:  -0.20 },
  'Africa/Addis_Ababa':     { city: 'Addis Ababa',       country: 'Ethiopia',                   lat:  9.02, lon:  38.74 },
  'Africa/Algiers':         { city: 'Algiers',           country: 'Algeria',                    lat: 36.74, lon:   3.06 },
  'Africa/Asmara':          { city: 'Asmara',            country: 'Eritrea',                    lat: 15.34, lon:  38.93 },
  'Africa/Bamako':          { city: 'Bamako',            country: 'Mali',                       lat: 12.65, lon:  -8.00 },
  'Africa/Bangui':          { city: 'Bangui',            country: 'CAR',                        lat:  4.36, lon:  18.55 },
  'Africa/Banjul':          { city: 'Banjul',            country: 'Gambia',                     lat: 13.45, lon: -16.58 },
  'Africa/Bissau':          { city: 'Bissau',            country: 'Guinea-Bissau',              lat: 11.86, lon: -15.60 },
  'Africa/Blantyre':        { city: 'Blantyre',          country: 'Malawi',                     lat:-15.79, lon:  35.00 },
  'Africa/Brazzaville':     { city: 'Brazzaville',       country: 'Congo',                      lat: -4.27, lon:  15.27 },
  'Africa/Bujumbura':       { city: 'Bujumbura',         country: 'Burundi',                    lat: -3.38, lon:  29.35 },
  'Africa/Cairo':           { city: 'Cairo',             country: 'Egypt',                      lat: 30.06, lon:  31.25 },
  'Africa/Casablanca':      { city: 'Casablanca',        country: 'Morocco',                    lat: 33.59, lon:  -7.62 },
  'Africa/Ceuta':           { city: 'Ceuta',             country: 'Spain',                      lat: 35.89, lon:  -5.31 },
  'Africa/Conakry':         { city: 'Conakry',           country: 'Guinea',                     lat:  9.54, lon: -13.68 },
  'Africa/Dakar':           { city: 'Dakar',             country: 'Senegal',                    lat: 14.69, lon: -17.44 },
  'Africa/Dar_es_Salaam':   { city: 'Dar es Salaam',     country: 'Tanzania',                   lat: -6.80, lon:  39.27 },
  'Africa/Djibouti':        { city: 'Djibouti',          country: 'Djibouti',                   lat: 11.59, lon:  43.15 },
  'Africa/Douala':          { city: 'Douala',            country: 'Cameroon',                   lat:  4.05, lon:   9.71 },
  'Africa/El_Aaiun':        { city: 'El Aaiun',          country: 'Western Sahara',             lat: 27.16, lon: -13.20 },
  'Africa/Freetown':        { city: 'Freetown',          country: 'Sierra Leone',               lat:  8.49, lon: -13.23 },
  'Africa/Gaborone':        { city: 'Gaborone',          country: 'Botswana',                   lat:-24.65, lon:  25.91 },
  'Africa/Harare':          { city: 'Harare',            country: 'Zimbabwe',                   lat:-17.82, lon:  31.05 },
  'Africa/Johannesburg':    { city: 'Johannesburg',      country: 'South Africa',               lat:-26.20, lon:  28.04 },
  'Africa/Juba':            { city: 'Juba',              country: 'South Sudan',                lat:  4.85, lon:  31.60 },
  'Africa/Kampala':         { city: 'Kampala',           country: 'Uganda',                     lat:  0.32, lon:  32.58 },
  'Africa/Khartoum':        { city: 'Khartoum',          country: 'Sudan',                      lat: 15.55, lon:  32.53 },
  'Africa/Kigali':          { city: 'Kigali',            country: 'Rwanda',                     lat: -1.95, lon:  30.06 },
  'Africa/Kinshasa':        { city: 'Kinshasa',          country: 'DR Congo',                   lat: -4.32, lon:  15.32 },
  'Africa/Lagos':           { city: 'Lagos',             country: 'Nigeria',                    lat:  6.45, lon:   3.40 },
  'Africa/Libreville':      { city: 'Libreville',        country: 'Gabon',                      lat:  0.39, lon:   9.45 },
  'Africa/Lome':            { city: 'Lomé',              country: 'Togo',                       lat:  6.14, lon:   1.21 },
  'Africa/Luanda':          { city: 'Luanda',            country: 'Angola',                     lat: -8.84, lon:  13.23 },
  'Africa/Lubumbashi':      { city: 'Lubumbashi',        country: 'DR Congo',                   lat:-11.68, lon:  27.47 },
  'Africa/Lusaka':          { city: 'Lusaka',            country: 'Zambia',                     lat:-15.42, lon:  28.28 },
  'Africa/Malabo':          { city: 'Malabo',            country: 'Equatorial Guinea',          lat:  3.75, lon:   8.78 },
  'Africa/Maputo':          { city: 'Maputo',            country: 'Mozambique',                 lat:-25.97, lon:  32.59 },
  'Africa/Maseru':          { city: 'Maseru',            country: 'Lesotho',                    lat:-29.32, lon:  27.48 },
  'Africa/Mbabane':         { city: 'Mbabane',           country: 'Eswatini',                   lat:-26.32, lon:  31.14 },
  'Africa/Mogadishu':       { city: 'Mogadishu',         country: 'Somalia',                    lat:  2.05, lon:  45.34 },
  'Africa/Monrovia':        { city: 'Monrovia',          country: 'Liberia',                    lat:  6.30, lon: -10.80 },
  'Africa/Nairobi':         { city: 'Nairobi',           country: 'Kenya',                      lat: -1.29, lon:  36.82 },
  'Africa/Ndjamena':        { city: "N'Djamena",         country: 'Chad',                       lat: 12.11, lon:  15.04 },
  'Africa/Niamey':          { city: 'Niamey',            country: 'Niger',                      lat: 13.51, lon:   2.12 },
  'Africa/Nouakchott':      { city: 'Nouakchott',        country: 'Mauritania',                 lat: 18.08, lon: -15.97 },
  'Africa/Ouagadougou':     { city: 'Ouagadougou',       country: 'Burkina Faso',               lat: 12.37, lon:  -1.53 },
  'Africa/Porto-Novo':      { city: 'Porto-Novo',        country: 'Benin',                      lat:  6.37, lon:   2.42 },
  'Africa/Sao_Tome':        { city: 'São Tomé',          country: 'São Tomé & Príncipe',        lat:  0.34, lon:   6.73 },
  'Africa/Tripoli':         { city: 'Tripoli',           country: 'Libya',                      lat: 32.90, lon:  13.18 },
  'Africa/Tunis':           { city: 'Tunis',             country: 'Tunisia',                    lat: 36.82, lon:  10.18 },
  'Africa/Windhoek':        { city: 'Windhoek',          country: 'Namibia',                    lat:-22.56, lon:  17.08 },
  // Americas
  'America/Adak':           { city: 'Adak',              country: 'United States',              lat: 51.88, lon:-176.65 },
  'America/Anchorage':      { city: 'Anchorage',         country: 'United States',              lat: 61.22, lon:-149.90 },
  'America/Araguaina':      { city: 'Araguaína',         country: 'Brazil',                     lat: -7.19, lon: -48.20 },
  'America/Argentina/Buenos_Aires': { city: 'Buenos Aires', country: 'Argentina',              lat:-34.60, lon: -58.38 },
  'America/Argentina/Catamarca':    { city: 'Catamarca',  country: 'Argentina',                 lat:-28.47, lon: -65.78 },
  'America/Argentina/Cordoba':      { city: 'Córdoba',    country: 'Argentina',                 lat:-31.42, lon: -64.18 },
  'America/Argentina/Jujuy':        { city: 'Jujuy',      country: 'Argentina',                 lat:-24.19, lon: -65.30 },
  'America/Argentina/La_Rioja':     { city: 'La Rioja',   country: 'Argentina',                 lat:-29.41, lon: -66.86 },
  'America/Argentina/Mendoza':      { city: 'Mendoza',    country: 'Argentina',                 lat:-32.89, lon: -68.83 },
  'America/Argentina/Rio_Gallegos': { city: 'Río Gallegos', country: 'Argentina',              lat:-51.62, lon: -69.22 },
  'America/Argentina/Salta':        { city: 'Salta',      country: 'Argentina',                 lat:-24.78, lon: -65.41 },
  'America/Argentina/San_Juan':     { city: 'San Juan',   country: 'Argentina',                 lat:-31.54, lon: -68.54 },
  'America/Argentina/San_Luis':     { city: 'San Luis',   country: 'Argentina',                 lat:-33.30, lon: -66.34 },
  'America/Argentina/Tucuman':      { city: 'Tucumán',    country: 'Argentina',                 lat:-26.82, lon: -65.22 },
  'America/Argentina/Ushuaia':      { city: 'Ushuaia',    country: 'Argentina',                 lat:-54.80, lon: -68.30 },
  'America/Asuncion':       { city: 'Asunción',          country: 'Paraguay',                   lat:-25.29, lon: -57.65 },
  'America/Bahia':          { city: 'Salvador',           country: 'Brazil',                     lat:-12.97, lon: -38.50 },
  'America/Bahia_Banderas': { city: 'Bahía de Banderas', country: 'Mexico',                     lat: 20.80, lon:-105.25 },
  'America/Barbados':       { city: 'Bridgetown',         country: 'Barbados',                   lat: 13.10, lon: -59.62 },
  'America/Belem':          { city: 'Belém',              country: 'Brazil',                     lat: -1.46, lon: -48.50 },
  'America/Belize':         { city: 'Belize City',        country: 'Belize',                     lat: 17.25, lon: -88.77 },
  'America/Boa_Vista':      { city: 'Boa Vista',          country: 'Brazil',                     lat:  2.82, lon: -60.67 },
  'America/Bogota':         { city: 'Bogotá',             country: 'Colombia',                   lat:  4.71, lon: -74.07 },
  'America/Boise':          { city: 'Boise',              country: 'United States',              lat: 43.62, lon:-116.20 },
  'America/Cambridge_Bay':  { city: 'Cambridge Bay',      country: 'Canada',                     lat: 69.12, lon:-105.05 },
  'America/Campo_Grande':   { city: 'Campo Grande',       country: 'Brazil',                     lat:-20.45, lon: -54.62 },
  'America/Cancun':         { city: 'Cancún',             country: 'Mexico',                     lat: 21.16, lon: -86.85 },
  'America/Caracas':        { city: 'Caracas',            country: 'Venezuela',                  lat: 10.49, lon: -66.88 },
  'America/Cayenne':        { city: 'Cayenne',            country: 'French Guiana',              lat:  4.94, lon: -52.33 },
  'America/Chicago':        { city: 'Chicago',            country: 'United States',              lat: 41.85, lon: -87.65 },
  'America/Chihuahua':      { city: 'Chihuahua',          country: 'Mexico',                     lat: 28.64, lon:-106.09 },
  'America/Costa_Rica':     { city: 'San José',           country: 'Costa Rica',                 lat:  9.93, lon: -84.08 },
  'America/Cuiaba':         { city: 'Cuiabá',             country: 'Brazil',                     lat:-15.60, lon: -56.10 },
  'America/Curacao':        { city: 'Willemstad',         country: 'Curaçao',                    lat: 12.11, lon: -68.93 },
  'America/Denver':         { city: 'Denver',             country: 'United States',              lat: 39.73, lon:-104.98 },
  'America/Detroit':        { city: 'Detroit',            country: 'United States',              lat: 42.33, lon: -83.05 },
  'America/Edmonton':       { city: 'Edmonton',           country: 'Canada',                     lat: 53.55, lon:-113.50 },
  'America/El_Salvador':    { city: 'San Salvador',       country: 'El Salvador',                lat: 13.69, lon: -89.19 },
  'America/Fortaleza':      { city: 'Fortaleza',          country: 'Brazil',                     lat: -3.72, lon: -38.54 },
  'America/Glace_Bay':      { city: 'Glace Bay',          country: 'Canada',                     lat: 46.20, lon: -59.96 },
  'America/Godthab':        { city: 'Nuuk',               country: 'Greenland',                  lat: 64.18, lon: -51.72 },
  'America/Nuuk':           { city: 'Nuuk',               country: 'Greenland',                  lat: 64.18, lon: -51.72 },
  'America/Goose_Bay':      { city: 'Goose Bay',          country: 'Canada',                     lat: 53.32, lon: -60.41 },
  'America/Grand_Turk':     { city: 'Cockburn Town',      country: 'Turks & Caicos',             lat: 21.46, lon: -71.14 },
  'America/Guatemala':      { city: 'Guatemala City',     country: 'Guatemala',                  lat: 14.62, lon: -90.52 },
  'America/Guayaquil':      { city: 'Guayaquil',          country: 'Ecuador',                    lat: -2.19, lon: -79.89 },
  'America/Guyana':         { city: 'Georgetown',         country: 'Guyana',                     lat:  6.80, lon: -58.16 },
  'America/Halifax':        { city: 'Halifax',            country: 'Canada',                     lat: 44.65, lon: -63.60 },
  'America/Havana':         { city: 'Havana',             country: 'Cuba',                       lat: 23.13, lon: -82.38 },
  'America/Hermosillo':     { city: 'Hermosillo',         country: 'Mexico',                     lat: 29.07, lon:-110.96 },
  'America/Indiana/Indianapolis': { city: 'Indianapolis', country: 'United States',             lat: 39.77, lon: -86.16 },
  'America/Jamaica':        { city: 'Kingston',           country: 'Jamaica',                    lat: 18.00, lon: -76.79 },
  'America/Juneau':         { city: 'Juneau',             country: 'United States',              lat: 58.30, lon:-134.42 },
  'America/Kentucky/Louisville': { city: 'Louisville',   country: 'United States',              lat: 38.25, lon: -85.76 },
  'America/La_Paz':         { city: 'La Paz',             country: 'Bolivia',                    lat:-16.50, lon: -68.15 },
  'America/Lima':           { city: 'Lima',               country: 'Peru',                       lat:-12.05, lon: -77.05 },
  'America/Los_Angeles':    { city: 'Los Angeles',        country: 'United States',              lat: 34.05, lon:-118.24 },
  'America/Maceio':         { city: 'Maceió',             country: 'Brazil',                     lat: -9.67, lon: -35.74 },
  'America/Managua':        { city: 'Managua',            country: 'Nicaragua',                  lat: 12.14, lon: -86.31 },
  'America/Manaus':         { city: 'Manaus',             country: 'Brazil',                     lat: -3.11, lon: -60.02 },
  'America/Martinique':     { city: 'Fort-de-France',     country: 'Martinique',                 lat: 14.61, lon: -61.08 },
  'America/Matamoros':      { city: 'Matamoros',          country: 'Mexico',                     lat: 25.87, lon: -97.50 },
  'America/Mazatlan':       { city: 'Mazatlán',           country: 'Mexico',                     lat: 23.22, lon:-106.42 },
  'America/Menominee':      { city: 'Menominee',          country: 'United States',              lat: 45.11, lon: -87.61 },
  'America/Merida':         { city: 'Mérida',             country: 'Mexico',                     lat: 20.97, lon: -89.62 },
  'America/Mexico_City':    { city: 'Mexico City',        country: 'Mexico',                     lat: 19.43, lon: -99.13 },
  'America/Miquelon':       { city: 'Saint-Pierre',       country: 'St. Pierre & Miquelon',      lat: 46.78, lon: -56.18 },
  'America/Moncton':        { city: 'Moncton',            country: 'Canada',                     lat: 46.09, lon: -64.80 },
  'America/Monterrey':      { city: 'Monterrey',          country: 'Mexico',                     lat: 25.68, lon:-100.32 },
  'America/Montevideo':     { city: 'Montevideo',         country: 'Uruguay',                    lat:-34.83, lon: -56.17 },
  'America/Nassau':         { city: 'Nassau',             country: 'Bahamas',                    lat: 25.05, lon: -77.35 },
  'America/New_York':       { city: 'New York',           country: 'United States',              lat: 40.71, lon: -74.01 },
  'America/Nome':           { city: 'Nome',               country: 'United States',              lat: 64.50, lon:-165.41 },
  'America/Noronha':        { city: 'Fernando de Noronha',country: 'Brazil',                     lat: -3.85, lon: -32.43 },
  'America/Ojinaga':        { city: 'Ojinaga',            country: 'Mexico',                     lat: 29.57, lon:-104.41 },
  'America/Panama':         { city: 'Panama City',        country: 'Panama',                     lat:  8.99, lon: -79.52 },
  'America/Paramaribo':     { city: 'Paramaribo',         country: 'Suriname',                   lat:  5.87, lon: -55.17 },
  'America/Phoenix':        { city: 'Phoenix',            country: 'United States',              lat: 33.45, lon:-112.07 },
  'America/Port-au-Prince': { city: 'Port-au-Prince',     country: 'Haiti',                      lat: 18.54, lon: -72.34 },
  'America/Port_of_Spain':  { city: 'Port of Spain',      country: 'Trinidad & Tobago',          lat: 10.65, lon: -61.52 },
  'America/Porto_Velho':    { city: 'Porto Velho',         country: 'Brazil',                    lat: -8.76, lon: -63.90 },
  'America/Puerto_Rico':    { city: 'San Juan',            country: 'Puerto Rico',                lat: 18.47, lon: -66.11 },
  'America/Punta_Arenas':   { city: 'Punta Arenas',        country: 'Chile',                     lat:-53.16, lon: -70.91 },
  'America/Recife':         { city: 'Recife',              country: 'Brazil',                     lat: -8.05, lon: -34.88 },
  'America/Regina':         { city: 'Regina',              country: 'Canada',                    lat: 50.45, lon:-104.62 },
  'America/Rio_Branco':     { city: 'Rio Branco',          country: 'Brazil',                    lat: -9.97, lon: -67.81 },
  'America/Santiago':       { city: 'Santiago',            country: 'Chile',                     lat:-33.46, lon: -70.65 },
  'America/Santo_Domingo':  { city: 'Santo Domingo',       country: 'Dominican Republic',        lat: 18.48, lon: -69.90 },
  'America/Sao_Paulo':      { city: 'São Paulo',           country: 'Brazil',                    lat:-23.55, lon: -46.63 },
  'America/Sitka':          { city: 'Sitka',               country: 'United States',             lat: 57.05, lon:-135.33 },
  'America/St_Johns':       { city: "St. John's",          country: 'Canada',                    lat: 47.56, lon: -52.71 },
  'America/St_Kitts':       { city: 'Basseterre',          country: 'Saint Kitts & Nevis',       lat: 17.30, lon: -62.72 },
  'America/St_Lucia':       { city: 'Castries',            country: 'Saint Lucia',               lat: 14.01, lon: -60.99 },
  'America/St_Thomas':      { city: 'Charlotte Amalie',    country: 'US Virgin Islands',         lat: 18.34, lon: -64.93 },
  'America/St_Vincent':     { city: 'Kingstown',           country: 'Saint Vincent',             lat: 13.16, lon: -61.22 },
  'America/Swift_Current':  { city: 'Swift Current',       country: 'Canada',                    lat: 50.29, lon:-107.80 },
  'America/Tegucigalpa':    { city: 'Tegucigalpa',         country: 'Honduras',                  lat: 14.09, lon: -87.21 },
  'America/Thunder_Bay':    { city: 'Thunder Bay',         country: 'Canada',                    lat: 48.38, lon: -89.25 },
  'America/Tijuana':        { city: 'Tijuana',             country: 'Mexico',                    lat: 32.52, lon:-117.04 },
  'America/Toronto':        { city: 'Toronto',             country: 'Canada',                    lat: 43.70, lon: -79.42 },
  'America/Vancouver':      { city: 'Vancouver',           country: 'Canada',                    lat: 49.25, lon:-123.12 },
  'America/Whitehorse':     { city: 'Whitehorse',          country: 'Canada',                    lat: 60.72, lon:-135.06 },
  'America/Winnipeg':       { city: 'Winnipeg',            country: 'Canada',                    lat: 49.90, lon: -97.14 },
  'America/Yakutat':        { city: 'Yakutat',             country: 'United States',             lat: 59.55, lon:-139.73 },
  'America/Yellowknife':    { city: 'Yellowknife',         country: 'Canada',                    lat: 62.45, lon:-114.38 },
  // Arctic
  'Arctic/Longyearbyen':    { city: 'Longyearbyen',        country: 'Svalbard',                  lat: 78.22, lon:  15.65 },
  // Asia
  'Asia/Aden':              { city: 'Aden',                country: 'Yemen',                     lat: 12.78, lon:  45.04 },
  'Asia/Almaty':            { city: 'Almaty',              country: 'Kazakhstan',                lat: 43.25, lon:  76.94 },
  'Asia/Amman':             { city: 'Amman',               country: 'Jordan',                    lat: 31.95, lon:  35.93 },
  'Asia/Anadyr':            { city: 'Anadyr',              country: 'Russia',                    lat: 64.73, lon: 177.52 },
  'Asia/Aqtau':             { city: 'Aqtau',               country: 'Kazakhstan',                lat: 43.65, lon:  51.20 },
  'Asia/Aqtobe':            { city: 'Aqtobe',              country: 'Kazakhstan',                lat: 50.28, lon:  57.20 },
  'Asia/Ashgabat':          { city: 'Ashgabat',            country: 'Turkmenistan',              lat: 37.95, lon:  58.38 },
  'Asia/Atyrau':            { city: 'Atyrau',              country: 'Kazakhstan',                lat: 47.12, lon:  51.88 },
  'Asia/Baghdad':           { city: 'Baghdad',             country: 'Iraq',                      lat: 33.34, lon:  44.40 },
  'Asia/Bahrain':           { city: 'Manama',              country: 'Bahrain',                   lat: 26.22, lon:  50.59 },
  'Asia/Baku':              { city: 'Baku',                country: 'Azerbaijan',                lat: 40.41, lon:  49.87 },
  'Asia/Bangkok':           { city: 'Bangkok',             country: 'Thailand',                  lat: 13.75, lon: 100.52 },
  'Asia/Barnaul':           { city: 'Barnaul',             country: 'Russia',                    lat: 53.35, lon:  83.79 },
  'Asia/Beirut':            { city: 'Beirut',              country: 'Lebanon',                   lat: 33.89, lon:  35.50 },
  'Asia/Bishkek':           { city: 'Bishkek',             country: 'Kyrgyzstan',                lat: 42.87, lon:  74.59 },
  'Asia/Brunei':            { city: 'Bandar Seri Begawan', country: 'Brunei',                    lat:  4.95, lon: 114.95 },
  'Asia/Chita':             { city: 'Chita',               country: 'Russia',                    lat: 52.04, lon: 113.50 },
  'Asia/Choibalsan':        { city: 'Choibalsan',          country: 'Mongolia',                  lat: 48.07, lon: 114.54 },
  'Asia/Colombo':           { city: 'Colombo',             country: 'Sri Lanka',                 lat:  6.93, lon:  79.85 },
  'Asia/Damascus':          { city: 'Damascus',            country: 'Syria',                     lat: 33.51, lon:  36.29 },
  'Asia/Dhaka':             { city: 'Dhaka',               country: 'Bangladesh',                lat: 23.72, lon:  90.41 },
  'Asia/Dili':              { city: 'Dili',                country: 'Timor-Leste',               lat: -8.56, lon: 125.58 },
  'Asia/Dubai':             { city: 'Dubai',               country: 'UAE',                       lat: 25.20, lon:  55.27 },
  'Asia/Dushanbe':          { city: 'Dushanbe',            country: 'Tajikistan',                lat: 38.56, lon:  68.77 },
  'Asia/Famagusta':         { city: 'Famagusta',           country: 'Cyprus',                    lat: 35.12, lon:  33.95 },
  'Asia/Gaza':              { city: 'Gaza',                country: 'Palestine',                 lat: 31.52, lon:  34.47 },
  'Asia/Hebron':            { city: 'Hebron',              country: 'Palestine',                 lat: 31.53, lon:  35.10 },
  'Asia/Ho_Chi_Minh':       { city: 'Ho Chi Minh City',    country: 'Vietnam',                   lat: 10.82, lon: 106.63 },
  'Asia/Hong_Kong':         { city: 'Hong Kong',           country: 'Hong Kong',                 lat: 22.32, lon: 114.17 },
  'Asia/Hovd':              { city: 'Hovd',                country: 'Mongolia',                  lat: 47.98, lon:  91.64 },
  'Asia/Irkutsk':           { city: 'Irkutsk',             country: 'Russia',                    lat: 52.29, lon: 104.28 },
  'Asia/Jakarta':           { city: 'Jakarta',             country: 'Indonesia',                 lat: -6.21, lon: 106.85 },
  'Asia/Jayapura':          { city: 'Jayapura',            country: 'Indonesia',                 lat: -2.53, lon: 140.72 },
  'Asia/Jerusalem':         { city: 'Jerusalem',           country: 'Israel',                    lat: 31.78, lon:  35.22 },
  'Asia/Kabul':             { city: 'Kabul',               country: 'Afghanistan',               lat: 34.53, lon:  69.17 },
  'Asia/Kamchatka':         { city: 'Petropavlovsk-Kamchatsky', country: 'Russia',              lat: 53.01, lon: 158.65 },
  'Asia/Karachi':           { city: 'Karachi',             country: 'Pakistan',                  lat: 24.86, lon:  67.01 },
  'Asia/Kathmandu':         { city: 'Kathmandu',           country: 'Nepal',                     lat: 27.71, lon:  85.31 },
  'Asia/Khandyga':          { city: 'Khandyga',            country: 'Russia',                    lat: 62.66, lon: 135.55 },
  'Asia/Kolkata':           { city: 'Kolkata',             country: 'India',                     lat: 22.57, lon:  88.36 },
  'Asia/Krasnoyarsk':       { city: 'Krasnoyarsk',         country: 'Russia',                    lat: 56.01, lon:  92.86 },
  'Asia/Kuala_Lumpur':      { city: 'Kuala Lumpur',        country: 'Malaysia',                  lat:  3.15, lon: 101.69 },
  'Asia/Kuching':           { city: 'Kuching',             country: 'Malaysia',                  lat:  1.55, lon: 110.33 },
  'Asia/Kuwait':            { city: 'Kuwait City',         country: 'Kuwait',                    lat: 29.37, lon:  47.98 },
  'Asia/Macau':             { city: 'Macau',               country: 'Macau',                     lat: 22.20, lon: 113.55 },
  'Asia/Magadan':           { city: 'Magadan',             country: 'Russia',                    lat: 59.57, lon: 150.77 },
  'Asia/Makassar':          { city: 'Makassar',            country: 'Indonesia',                 lat: -5.13, lon: 119.42 },
  'Asia/Manila':            { city: 'Manila',              country: 'Philippines',               lat: 14.60, lon: 120.98 },
  'Asia/Muscat':            { city: 'Muscat',              country: 'Oman',                      lat: 23.62, lon:  58.59 },
  'Asia/Nicosia':           { city: 'Nicosia',             country: 'Cyprus',                    lat: 35.17, lon:  33.37 },
  'Asia/Novokuznetsk':      { city: 'Novokuznetsk',        country: 'Russia',                    lat: 53.76, lon:  87.11 },
  'Asia/Novosibirsk':       { city: 'Novosibirsk',         country: 'Russia',                    lat: 54.99, lon:  82.90 },
  'Asia/Omsk':              { city: 'Omsk',                country: 'Russia',                    lat: 54.97, lon:  73.38 },
  'Asia/Oral':              { city: 'Oral',                country: 'Kazakhstan',                lat: 51.23, lon:  51.36 },
  'Asia/Phnom_Penh':        { city: 'Phnom Penh',          country: 'Cambodia',                  lat: 11.56, lon: 104.92 },
  'Asia/Pontianak':         { city: 'Pontianak',           country: 'Indonesia',                 lat: -0.02, lon: 109.34 },
  'Asia/Pyongyang':         { city: 'Pyongyang',           country: 'North Korea',               lat: 39.02, lon: 125.75 },
  'Asia/Qatar':             { city: 'Doha',                country: 'Qatar',                     lat: 25.29, lon:  51.53 },
  'Asia/Qostanay':          { city: 'Qostanay',            country: 'Kazakhstan',                lat: 53.21, lon:  63.63 },
  'Asia/Qyzylorda':         { city: 'Qyzylorda',           country: 'Kazakhstan',                lat: 44.85, lon:  65.51 },
  'Asia/Riyadh':            { city: 'Riyadh',              country: 'Saudi Arabia',              lat: 24.69, lon:  46.72 },
  'Asia/Sakhalin':          { city: 'Yuzhno-Sakhalinsk',   country: 'Russia',                    lat: 46.96, lon: 142.74 },
  'Asia/Samarkand':         { city: 'Samarkand',           country: 'Uzbekistan',                lat: 39.65, lon:  66.96 },
  'Asia/Seoul':             { city: 'Seoul',               country: 'South Korea',               lat: 37.57, lon: 126.98 },
  'Asia/Shanghai':          { city: 'Shanghai',            country: 'China',                     lat: 31.23, lon: 121.47 },
  'Asia/Singapore':         { city: 'Singapore',           country: 'Singapore',                 lat:  1.29, lon: 103.85 },
  'Asia/Srednekolymsk':     { city: 'Srednekolymsk',       country: 'Russia',                    lat: 67.46, lon: 153.71 },
  'Asia/Taipei':            { city: 'Taipei',              country: 'Taiwan',                    lat: 25.05, lon: 121.53 },
  'Asia/Tashkent':          { city: 'Tashkent',            country: 'Uzbekistan',                lat: 41.30, lon:  69.27 },
  'Asia/Tbilisi':           { city: 'Tbilisi',             country: 'Georgia',                   lat: 41.69, lon:  44.83 },
  'Asia/Tehran':            { city: 'Tehran',              country: 'Iran',                      lat: 35.69, lon:  51.42 },
  'Asia/Thimphu':           { city: 'Thimphu',             country: 'Bhutan',                    lat: 27.47, lon:  89.64 },
  'Asia/Tokyo':             { city: 'Tokyo',               country: 'Japan',                     lat: 35.69, lon: 139.69 },
  'Asia/Tomsk':             { city: 'Tomsk',               country: 'Russia',                    lat: 56.50, lon:  84.97 },
  'Asia/Ulaanbaatar':       { city: 'Ulaanbaatar',         country: 'Mongolia',                  lat: 47.91, lon: 106.88 },
  'Asia/Urumqi':            { city: 'Ürümqi',              country: 'China',                     lat: 43.79, lon:  87.60 },
  'Asia/Ust-Nera':          { city: 'Ust-Nera',            country: 'Russia',                    lat: 64.56, lon: 143.20 },
  'Asia/Vientiane':         { city: 'Vientiane',           country: 'Laos',                      lat: 17.97, lon: 102.60 },
  'Asia/Vladivostok':       { city: 'Vladivostok',         country: 'Russia',                    lat: 43.10, lon: 131.88 },
  'Asia/Yakutsk':           { city: 'Yakutsk',             country: 'Russia',                    lat: 62.03, lon: 129.73 },
  'Asia/Yangon':            { city: 'Yangon',              country: 'Myanmar',                   lat: 16.86, lon:  96.19 },
  'Asia/Yekaterinburg':     { city: 'Yekaterinburg',       country: 'Russia',                    lat: 56.84, lon:  60.60 },
  'Asia/Yerevan':           { city: 'Yerevan',             country: 'Armenia',                   lat: 40.18, lon:  44.51 },
  // Atlantic
  'Atlantic/Azores':        { city: 'Ponta Delgada',       country: 'Portugal (Azores)',          lat: 37.74, lon: -25.67 },
  'Atlantic/Bermuda':       { city: 'Hamilton',            country: 'Bermuda',                   lat: 32.30, lon: -64.79 },
  'Atlantic/Canary':        { city: 'Las Palmas',          country: 'Spain (Canary Is.)',         lat: 28.10, lon: -15.41 },
  'Atlantic/Cape_Verde':    { city: 'Praia',               country: 'Cape Verde',                lat: 14.93, lon: -23.51 },
  'Atlantic/Faroe':         { city: 'Tórshavn',            country: 'Faroe Islands',             lat: 62.01, lon:  -6.79 },
  'Atlantic/Madeira':       { city: 'Funchal',             country: 'Portugal (Madeira)',         lat: 32.65, lon: -16.92 },
  'Atlantic/Reykjavik':     { city: 'Reykjavik',           country: 'Iceland',                   lat: 64.13, lon: -21.94 },
  'Atlantic/South_Georgia': { city: 'King Edward Point',   country: 'South Georgia',             lat:-54.28, lon: -36.49 },
  'Atlantic/St_Helena':     { city: 'Jamestown',           country: 'Saint Helena',              lat:-15.93, lon:  -5.72 },
  'Atlantic/Stanley':       { city: 'Stanley',             country: 'Falkland Islands',          lat:-51.70, lon: -57.85 },
  // Australia
  'Australia/Adelaide':     { city: 'Adelaide',            country: 'Australia',                 lat:-34.93, lon: 138.60 },
  'Australia/Brisbane':     { city: 'Brisbane',            country: 'Australia',                 lat:-27.47, lon: 153.03 },
  'Australia/Broken_Hill':  { city: 'Broken Hill',         country: 'Australia',                 lat:-31.96, lon: 141.45 },
  'Australia/Darwin':       { city: 'Darwin',              country: 'Australia',                 lat:-12.46, lon: 130.84 },
  'Australia/Eucla':        { city: 'Eucla',               country: 'Australia',                 lat:-31.68, lon: 128.88 },
  'Australia/Hobart':       { city: 'Hobart',              country: 'Australia',                 lat:-42.88, lon: 147.33 },
  'Australia/Lord_Howe':    { city: 'Lord Howe Island',    country: 'Australia',                 lat:-31.53, lon: 159.08 },
  'Australia/Melbourne':    { city: 'Melbourne',           country: 'Australia',                 lat:-37.81, lon: 144.96 },
  'Australia/Perth':        { city: 'Perth',               country: 'Australia',                 lat:-31.95, lon: 115.86 },
  'Australia/Sydney':       { city: 'Sydney',              country: 'Australia',                 lat:-33.87, lon: 151.21 },
  // Europe
  'Europe/Amsterdam':       { city: 'Amsterdam',           country: 'Netherlands',               lat: 52.37, lon:   4.90 },
  'Europe/Andorra':         { city: 'Andorra la Vella',    country: 'Andorra',                   lat: 42.51, lon:   1.52 },
  'Europe/Astrakhan':       { city: 'Astrakhan',           country: 'Russia',                    lat: 46.35, lon:  48.04 },
  'Europe/Athens':          { city: 'Athens',              country: 'Greece',                    lat: 37.97, lon:  23.72 },
  'Europe/Belgrade':        { city: 'Belgrade',            country: 'Serbia',                    lat: 44.80, lon:  20.46 },
  'Europe/Berlin':          { city: 'Berlin',              country: 'Germany',                   lat: 52.52, lon:  13.41 },
  'Europe/Bratislava':      { city: 'Bratislava',          country: 'Slovakia',                  lat: 48.15, lon:  17.11 },
  'Europe/Brussels':        { city: 'Brussels',            country: 'Belgium',                   lat: 50.85, lon:   4.35 },
  'Europe/Bucharest':       { city: 'Bucharest',           country: 'Romania',                   lat: 44.43, lon:  26.10 },
  'Europe/Budapest':        { city: 'Budapest',            country: 'Hungary',                   lat: 47.50, lon:  19.04 },
  'Europe/Chisinau':        { city: 'Chișinău',            country: 'Moldova',                   lat: 47.01, lon:  28.86 },
  'Europe/Copenhagen':      { city: 'Copenhagen',          country: 'Denmark',                   lat: 55.68, lon:  12.57 },
  'Europe/Dublin':          { city: 'Dublin',              country: 'Ireland',                   lat: 53.33, lon:  -6.25 },
  'Europe/Gibraltar':       { city: 'Gibraltar',           country: 'Gibraltar',                 lat: 36.14, lon:  -5.35 },
  'Europe/Helsinki':        { city: 'Helsinki',            country: 'Finland',                   lat: 60.17, lon:  24.94 },
  'Europe/Istanbul':        { city: 'Istanbul',            country: 'Turkey',                    lat: 41.01, lon:  28.96 },
  'Europe/Kaliningrad':     { city: 'Kaliningrad',         country: 'Russia',                    lat: 54.71, lon:  20.52 },
  'Europe/Kiev':            { city: 'Kyiv',                country: 'Ukraine',                   lat: 50.45, lon:  30.52 },
  'Europe/Kirov':           { city: 'Kirov',               country: 'Russia',                    lat: 58.60, lon:  49.65 },
  'Europe/Lisbon':          { city: 'Lisbon',              country: 'Portugal',                  lat: 38.72, lon:  -9.14 },
  'Europe/Ljubljana':       { city: 'Ljubljana',           country: 'Slovenia',                  lat: 46.05, lon:  14.51 },
  'Europe/London':          { city: 'London',              country: 'United Kingdom',            lat: 51.51, lon:  -0.13 },
  'Europe/Luxembourg':      { city: 'Luxembourg City',     country: 'Luxembourg',                lat: 49.61, lon:   6.13 },
  'Europe/Madrid':          { city: 'Madrid',              country: 'Spain',                     lat: 40.42, lon:  -3.70 },
  'Europe/Malta':           { city: 'Valletta',            country: 'Malta',                     lat: 35.90, lon:  14.51 },
  'Europe/Minsk':           { city: 'Minsk',               country: 'Belarus',                   lat: 53.90, lon:  27.57 },
  'Europe/Monaco':          { city: 'Monaco',              country: 'Monaco',                    lat: 43.73, lon:   7.42 },
  'Europe/Moscow':          { city: 'Moscow',              country: 'Russia',                    lat: 55.75, lon:  37.62 },
  'Europe/Nicosia':         { city: 'Nicosia',             country: 'Cyprus',                    lat: 35.17, lon:  33.37 },
  'Europe/Oslo':            { city: 'Oslo',                country: 'Norway',                    lat: 59.91, lon:  10.75 },
  'Europe/Paris':           { city: 'Paris',               country: 'France',                    lat: 48.86, lon:   2.35 },
  'Europe/Podgorica':       { city: 'Podgorica',           country: 'Montenegro',                lat: 42.44, lon:  19.27 },
  'Europe/Prague':          { city: 'Prague',              country: 'Czech Republic',            lat: 50.09, lon:  14.42 },
  'Europe/Riga':            { city: 'Riga',                country: 'Latvia',                    lat: 56.95, lon:  24.11 },
  'Europe/Rome':            { city: 'Rome',                country: 'Italy',                     lat: 41.89, lon:  12.48 },
  'Europe/Samara':          { city: 'Samara',              country: 'Russia',                    lat: 53.19, lon:  50.15 },
  'Europe/San_Marino':      { city: 'San Marino',          country: 'San Marino',                lat: 43.94, lon:  12.46 },
  'Europe/Sarajevo':        { city: 'Sarajevo',            country: 'Bosnia & Herzegovina',      lat: 43.85, lon:  18.39 },
  'Europe/Saratov':         { city: 'Saratov',             country: 'Russia',                    lat: 51.54, lon:  46.01 },
  'Europe/Simferopol':      { city: 'Simferopol',          country: 'Crimea',                    lat: 44.95, lon:  34.10 },
  'Europe/Skopje':          { city: 'Skopje',              country: 'North Macedonia',           lat: 41.99, lon:  21.43 },
  'Europe/Sofia':           { city: 'Sofia',               country: 'Bulgaria',                  lat: 42.70, lon:  23.33 },
  'Europe/Stockholm':       { city: 'Stockholm',           country: 'Sweden',                    lat: 59.33, lon:  18.07 },
  'Europe/Tallinn':         { city: 'Tallinn',             country: 'Estonia',                   lat: 59.44, lon:  24.75 },
  'Europe/Tirane':          { city: 'Tirana',              country: 'Albania',                   lat: 41.33, lon:  19.82 },
  'Europe/Ulyanovsk':       { city: 'Ulyanovsk',           country: 'Russia',                    lat: 54.31, lon:  48.40 },
  'Europe/Uzhgorod':        { city: 'Uzhhorod',            country: 'Ukraine',                   lat: 48.62, lon:  22.30 },
  'Europe/Vaduz':           { city: 'Vaduz',               country: 'Liechtenstein',             lat: 47.14, lon:   9.52 },
  'Europe/Vatican':         { city: 'Vatican City',        country: 'Vatican',                   lat: 41.90, lon:  12.45 },
  'Europe/Vienna':          { city: 'Vienna',              country: 'Austria',                   lat: 48.21, lon:  16.37 },
  'Europe/Vilnius':         { city: 'Vilnius',             country: 'Lithuania',                 lat: 54.69, lon:  25.28 },
  'Europe/Volgograd':       { city: 'Volgograd',           country: 'Russia',                    lat: 48.72, lon:  44.51 },
  'Europe/Warsaw':          { city: 'Warsaw',              country: 'Poland',                    lat: 52.23, lon:  21.01 },
  'Europe/Zagreb':          { city: 'Zagreb',              country: 'Croatia',                   lat: 45.81, lon:  15.98 },
  'Europe/Zaporozhye':      { city: 'Zaporizhzhia',        country: 'Ukraine',                   lat: 47.84, lon:  35.14 },
  'Europe/Zurich':          { city: 'Zurich',              country: 'Switzerland',               lat: 47.38, lon:   8.54 },
  // Indian Ocean
  'Indian/Antananarivo':    { city: 'Antananarivo',        country: 'Madagascar',                lat:-18.91, lon:  47.53 },
  'Indian/Chagos':          { city: 'Diego Garcia',        country: 'BIOT',                      lat: -7.32, lon:  72.42 },
  'Indian/Christmas':       { city: 'Flying Fish Cove',    country: 'Christmas Island',          lat:-10.49, lon: 105.63 },
  'Indian/Cocos':           { city: 'West Island',         country: 'Cocos Islands',             lat:-12.19, lon:  96.84 },
  'Indian/Comoro':          { city: 'Moroni',              country: 'Comoros',                   lat:-11.70, lon:  43.26 },
  'Indian/Kerguelen':       { city: 'Port-aux-Français',   country: 'French Southern Territories', lat:-49.35, lon: 70.22 },
  'Indian/Mahe':            { city: 'Victoria',            country: 'Seychelles',                lat: -4.62, lon:  55.45 },
  'Indian/Maldives':        { city: 'Malé',                country: 'Maldives',                  lat:  4.18, lon:  73.51 },
  'Indian/Mauritius':       { city: 'Port Louis',          country: 'Mauritius',                 lat:-20.16, lon:  57.50 },
  'Indian/Mayotte':         { city: 'Mamoudzou',           country: 'Mayotte',                   lat:-12.78, lon:  45.23 },
  'Indian/Reunion':         { city: 'Saint-Denis',         country: 'Réunion',                   lat:-20.88, lon:  55.45 },
  // Pacific
  'Pacific/Apia':           { city: 'Apia',                country: 'Samoa',                     lat:-13.83, lon:-171.77 },
  'Pacific/Auckland':       { city: 'Auckland',            country: 'New Zealand',               lat:-36.87, lon: 174.77 },
  'Pacific/Bougainville':   { city: 'Arawa',               country: 'Papua New Guinea',          lat: -6.23, lon: 155.57 },
  'Pacific/Chatham':        { city: 'Waitangi',            country: 'New Zealand (Chatham)',      lat:-43.95, lon:-176.56 },
  'Pacific/Chuuk':          { city: 'Weno',                country: 'Micronesia',                lat:  7.45, lon: 151.85 },
  'Pacific/Easter':         { city: 'Hanga Roa',           country: 'Chile (Easter Is.)',         lat:-27.15, lon:-109.43 },
  'Pacific/Efate':          { city: 'Port Vila',           country: 'Vanuatu',                   lat:-17.73, lon: 168.32 },
  'Pacific/Fakaofo':        { city: 'Fakaofo',             country: 'Tokelau',                   lat: -9.38, lon:-171.22 },
  'Pacific/Fiji':           { city: 'Suva',                country: 'Fiji',                      lat:-18.14, lon: 178.44 },
  'Pacific/Funafuti':       { city: 'Funafuti',            country: 'Tuvalu',                    lat: -8.52, lon: 179.20 },
  'Pacific/Galapagos':      { city: 'Puerto Baquerizo Moreno', country: 'Ecuador (Galápagos)',   lat: -0.90, lon: -89.61 },
  'Pacific/Gambier':        { city: 'Rikitea',             country: 'French Polynesia',          lat:-23.12, lon:-134.97 },
  'Pacific/Guadalcanal':    { city: 'Honiara',             country: 'Solomon Islands',           lat: -9.43, lon: 160.05 },
  'Pacific/Guam':           { city: 'Hagåtña',             country: 'Guam',                      lat: 13.47, lon: 144.75 },
  'Pacific/Honolulu':       { city: 'Honolulu',            country: 'United States (Hawaii)',     lat: 21.32, lon:-157.83 },
  'Pacific/Kiritimati':     { city: 'Kiritimati',          country: 'Kiribati',                  lat:  1.87, lon:-157.43 },
  'Pacific/Kosrae':         { city: 'Tofol',               country: 'Micronesia',                lat:  5.31, lon: 163.01 },
  'Pacific/Kwajalein':      { city: 'Majuro',              country: 'Marshall Islands',          lat:  7.12, lon: 171.13 },
  'Pacific/Majuro':         { city: 'Majuro',              country: 'Marshall Islands',          lat:  7.12, lon: 171.13 },
  'Pacific/Marquesas':      { city: 'Taiohae',             country: 'French Polynesia',          lat: -8.93, lon:-140.10 },
  'Pacific/Midway':         { city: 'Midway Atoll',        country: 'United States',             lat: 28.20, lon:-177.38 },
  'Pacific/Nauru':          { city: 'Yaren',               country: 'Nauru',                     lat: -0.55, lon: 166.92 },
  'Pacific/Niue':           { city: 'Alofi',               country: 'Niue',                      lat:-19.06, lon:-169.92 },
  'Pacific/Norfolk':        { city: 'Kingston',            country: 'Norfolk Island',            lat:-29.06, lon: 167.96 },
  'Pacific/Noumea':         { city: 'Nouméa',              country: 'New Caledonia',             lat:-22.27, lon: 166.46 },
  'Pacific/Pago_Pago':      { city: 'Pago Pago',           country: 'American Samoa',            lat:-14.27, lon:-170.70 },
  'Pacific/Palau':          { city: 'Ngerulmud',           country: 'Palau',                     lat:  7.50, lon: 134.62 },
  'Pacific/Pitcairn':       { city: 'Adamstown',           country: 'Pitcairn Islands',          lat:-25.07, lon:-130.10 },
  'Pacific/Pohnpei':        { city: 'Palikir',             country: 'Micronesia',                lat:  6.92, lon: 158.16 },
  'Pacific/Port_Moresby':   { city: 'Port Moresby',        country: 'Papua New Guinea',          lat: -9.45, lon: 147.18 },
  'Pacific/Rarotonga':      { city: 'Avarua',              country: 'Cook Islands',              lat:-21.21, lon:-159.78 },
  'Pacific/Saipan':         { city: 'Saipan',              country: 'Northern Mariana Islands',  lat: 15.18, lon: 145.75 },
  'Pacific/Tahiti':         { city: 'Papeete',             country: 'French Polynesia',          lat:-17.53, lon:-149.56 },
  'Pacific/Tarawa':         { city: 'South Tarawa',        country: 'Kiribati',                  lat:  1.33, lon: 173.02 },
  'Pacific/Tongatapu':      { city: "Nuku'alofa",          country: 'Tonga',                     lat:-21.14, lon:-175.22 },
  'Pacific/Wake':           { city: 'Wake Island',         country: 'United States',             lat: 19.28, lon: 166.64 },
  'Pacific/Wallis':         { city: 'Mata-Utu',            country: 'Wallis & Futuna',           lat:-13.28, lon:-176.18 },
  // UTC
  'UTC': { city: 'UTC', country: 'Universal', lat: 0, lon: 0 },
};

/**
 * Resolve the device's IANA timezone to a location instantly.
 * Falls back to a UTC-offset-derived equatorial point if the zone
 * isn't in the table — Open-Meteo still gets valid coordinates.
 */
export function getDeviceLocation(): TZLocation & { timezone: string } {
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
  const loc = TIMEZONE_LOCATION[tz];
  if (loc) return { ...loc, timezone: tz };

  // Unknown zone: derive approx longitude from UTC offset so weather coords
  // are at least in the right hemisphere.
  const offsetMin = -new Date().getTimezoneOffset();
  const lon = Math.max(-179, Math.min(179, (offsetMin / 60) * 15));
  return { city: tz.split('/').pop()?.replace(/_/g, ' ') ?? 'Your location', country: '', lat: 0, lon, timezone: tz };
}
